version: 0.1
frontend:
  phases:
  
   install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/angular-crud-client
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
